### ISSUE TITLE
Client not defined issue 

### ISSUE THREAD

**Issue by Rexdomine** [maksimKorzh/code-monkey-search#1]
hi please, I keep getting this issue when running crawler.py 

Traceback (most recent call last):
  File "crawler.py", line 93, in <module>
    crawler.crawl('http://portal.uea.ac.uk/', 5)
  File "crawler.py", line 82, in crawl
    self.crawl(link['href'], depth - 1)
  File "crawler.py", line 82, in crawl
    self.crawl(link['href'], depth - 1)
  File "crawler.py", line 82, in crawl
    self.crawl(link['href'], depth - 1)
  [Previous line repeated 1 more time]
  File "crawler.py", line 89, in crawl
    client.close()
NameError: name 'client' is not defined

**Comment by amide-init** [comment]
Add one more exception handler 
```
except NameError:
            pass
```
